name: admin_app
description: "Admin application for the Uber Clone project"
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.4"

dependencies:
  flutter:
    sdk: flutter
  uber_shared:
    path: ../../flutter-packages/uber_shared
  http: ^1.6.0
  shared_preferences: ^2.0.15
  socket_io_client: ^2.0.0
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  flutter_map: ^8.2.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true